### PR TITLE
Add Apache-2.0 license

### PR DESCRIPTION
**Pull request by oli-obk**
@mbr @phil-opp I need a comment from you in this PR that you accept the new licenses

I accept that all my contributions are dual licensed under MIT and Apache 2.0

### CODE REVIEW

**Comment by phil-opp** [comment]
I accept that all my contributions are dual licensed under MIT and Apache 2.0

**Comment by oli-obk** [comment]
ping @mbr

**Comment by mbr** [comment]
I accept that all my contributions are dual licensed under MIT and Apache 2.0.

**Comment by mbr** [comment]
for you, anything ;)

**Pull request merged**
