### PR TITLE
Remove board specific types and separate abstractions from register definitions

### PR DESCRIPTION
**Pull request by phil-opp**
Future design plans:

The `embedded` crate is a collection of various register structs, interfaces, drivers, and other abstractions. For each board/MCU/etc., we create an `embedded_xxx` crate that provides board-specific things such as a `Hardware` struct ([example](https://github.com/embed-rs/embedded_stm32f7/blob/76eaeec52b9beff7d803a328af11f75d839b33b2/src/lib.rs#L70)) or additional register structs.

The users can always choose if they want to use some abstraction (e.g. the convenient but runtime-check-based GPIO interface included in this PR) or if they want to operate on the registers directly.

### CODE REVIEW

**Comment by phil-opp** [comment]
cc @mbr @oli-obk

**Comment by mbr** [comment]
Looks good to me. No objections, but please rebase when merging =).

**Comment by phil-opp** [comment]
@mbr rebase? I think the branch is up-to-date… Or do you mean github's "rebase and merge" feature?

**Review by oli-obk — APPROVED** [review]
Lgtm, too

**Comment by mbr** [comment]
> @mbr rebase? I think the branch is up-to-date… Or do you mean github's "rebase and merge" feature?

The rebase and merge feature. Since we're greenfielding, it might be nice to enforce a linear history.

But I don't want to derail the discussion, just merge it if you like (Both you and @oli-obk should have the formerly missing permissions now).

**Review by mbr — APPROVED** [review]
I am @mbr and I approve this pull request.

**Comment by oli-obk** [comment]
> The rebase and merge feature. Since we're greenfielding, it might be nice to enforce a linear history.

I'm in full agreement with this. I disabled regular merging on this repository, so we can't accidentally mess up.

**Pull request merged**
